version: "2"

services:
  dbconnect:
    build: /vagrant/web/api/dbconnect
    networks:
      web_net:
        ipv4_address: 172.98.0.5



networks:
  web_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.98.0.0/16
          gateway: 172.98.0.1
